manipulator:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.0050000000000000001
  kinematics_solver_timeout: 0.0050000000000000001

  # kinematics_solver: pick_ik/PickIkPlugin
  # kinematics_solver_timeout: 0.005
  # kinematics_solver_attempts: 2
  # mode: global
  # position_scale: 1.0
  # rotation_scale: 0.5
  # position_threshold: 0.001
  # orientation_threshold: 0.0001
  # cost_threshold: 0.001
  # minimal_displacement_weight: 0.0
  # gd_step_size: 0.0001

  # kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
  # kinematics_solver_timeout: 0.007
  # position_only_ik: false
  # solve_type: Manipulation2 # Speed, Distance, Manipulation1, Manipulation2T